name: Deploy to server #directiva inicial

on: push
#  push: evento que dispara el flujo de trabajo
 #   branches: rama en la que se ejecuta el flujo de trabajo
 #     - main nombre de la rama
jobs: #trabajos que se ejecutan en el flujo de trabajo
  first_jobs: #nombre del trabajo
    runs-on: ubuntu-latest #sistema operativo en el que se ejecuta el trabajo
    env:
     NAME: codigo facilito
    steps:
     - name: Hola mundo
       run: echo "Hola mundo $NAME" #comando que se ejecuta en el trabajo
     #- name: ver archivo PHP  
      # run: cat hola.php $NAME #comando que se ejecuta en el trabajo
  second_jobs: #nombre del segundo trabajo
    #if: ${{ github.ref == 'refs/heads/main' &&  ||}} #condición para ejecutar el segundo trabajo
    if: success() #condición para ejecutar el segundo trabajo si el anterior fue exitoso
    #if: failure() #condición para ejecutar el segundo trabajo si el anterior falló
    needs: 
      - first_jobs #dependencia del primer trabajo
    runs-on: ubuntu-latest #sistema operativo en el que se ejecuta el trabajo
    steps:
       
     - name: Hola mundo 2
       #if: false #condición para ejecutar el segundo trabajo
       run: echo "Hola mundo ${{github.ref}}" #comando que se ejecuta en el segundo trabajo
     - name: ver variable de entorno 

       run: echo "La variable de entorno de el job anterior ${{ needs.first_jobs.outputs.name_value }}" #comando que se ejecuta en el segundo trabajo  