name: Deploy to server #directiva inicial

on: push
#  push: evento que dispara el flujo de trabajo
 #   branches: rama en la que se ejecuta el flujo de trabajo
 #     - main nombre de la rama
jobs: #trabajos que se ejecutan en el flujo de trabajo
  first_jobs: #nombre del trabajo
    runs-on: ubuntu-latest #sistema operativo en el que se ejecuta el trabajo
    steps:
     - name: Hola mundo
       run: echo "Hola mundo" #comando que se ejecuta en el trabajo
  second_jobs: #nombre del segundo trabajo
    needs: 
      - first_jobs #dependencia del primer trabajo
    runs-on: ubuntu-latest #sistema operativo en el que se ejecuta el trabajo
    steps:
     - name: Hola mundo 2
       run: echo "Hola mundo 2" #comando que se ejecuta en el segundo trabajo