name: Deploy to server #directiva inicial

on: push
#  push: evento que dispara el flujo de trabajo
 #   branches: rama en la que se ejecuta el flujo de trabajo
 #     - main nombre de la rama
jobs: #trabajos que se ejecutan en el flujo de trabajo
  first_jobs: #nombre del trabajo
    runs-on: ubuntu-latest #sistema operativo en el que se ejecuta el trabajo
    outputs:
      salida: hola job 1 
      salida2: ${{steps.step1.outputs.variable}} #variable de salida del trabajo
    env:
     NAME: codigo facilito
    steps:
     - name: Hola mundo
       
       run: echo "Hola mundo $NAME" #comando que se ejecuta en el trabajo
     - name: working dir
       run: ls -al #comando que se ejecuta en el trabajo para listar archivos
     - name: action
       uses: actions/checkout@v4   #acción que se ejecuta en el trabajo
     - name: working dir after action
       run: ls -al #comando que se ejecuta en el trabajo para listar archivos después de la acción
     - name: $GITHUB_OUTPUT
       id: step1
       run: echo "variable=DANDO VALOR" >> $GITHUB_OUTPUT #comando que se ejecuta en el trabajo para establecer una variable de salida
     - name: obtener mensaje
       run: echo "${{steps.step1.outputs.variable}}" #comando que se ejecuta en el trabajo para obtener el valor de la variable de salida
     #- name: ver archivo PHP  
      # run: cat hola.php $NAME #comando que se ejecuta en el trabajo
  second_jobs: #nombre del segundo trabajo
    #if: ${{ github.ref == 'refs/heads/main' &&  ||}} #condición para ejecutar el segundo trabajo
    if: success() #condición para ejecutar el segundo trabajo si el anterior fue exitoso
    #if: failure() #condición para ejecutar el segundo trabajo si el anterior falló
    needs: 
      - first_jobs #dependencia del primer trabajo
    runs-on: ubuntu-latest #sistema operativo en el que se ejecuta el trabajo
    env:
      SALIDA: ${{ needs.first_jobs.outputs.salida }} #variable de entorno que obtiene el valor de la salida del primer trabajo
      SALIDA2: ${{ needs.first_jobs.outputs.salida2 }} #variable de entorno que obtiene el valor de la salida del primer trabajo
    steps:
     - name: Hola mundo 1
       run: echo "Hola mundo ${{ env.SALIDA }}" #comando que se ejecuta en el segundo trabajo  
     - name: hola mundo 1.5
       run: echo "Hola mundo ${{ env.SALIDA2 }}" #comando que se ejecuta en el segundo trabajo para obtener la salida de la variable de salida del primer trabajo
     - name: Hola mundo 2
       #if: false #condición para ejecutar el segundo trabajo
       run: echo "Hola mundo ${{github.ref}}" #comando que se ejecuta en el segundo trabajo
     - name: ver variable de entorno 

       run: echo "La variable de entorno de el job anterior ${{ needs.first_jobs.outputs.name_value }}" #comando que se ejecuta en el segundo trabajo  
     - name: genear archivo
       run: |
        echo "archivo prueva, hola" >>test.log
     - name: subir artefacto
       uses: actions/upload-artifact@v4 #acción que se ejecuta en el trabajo para subir un artefacto
       with:
          name: archivos test #nombre del artefacto
          path: test.log
  third_jobs: #nombre del tercer trabajo
    runs-on: ubuntu-latest #sistema operativo en el que se ejecuta el trabajo

    steps:
     - name: descargar artefacto
       uses: actions/download-artifact@v4 #acción que se ejecuta en el trabajo para descargar un artefacto
       with:
          name: archivos test #nombre del artefacto
     - name: cat file
       run: cat test.log #comando que se ejecuta en el trabajo para mostrar el contenido del archivo descargado
